# Generated by Django 6.1.1 on 2026-10-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.CharField(blank=True, default='', max_length=50)),
                ('form', models.CharField(blank=True, default='', max_length=30)),
                ('frequency', models.CharField(blank=True, default='', max_length=50)),
                ('time', models.CharField(blank=True, default='', max_length=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reminder', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_records', to='onboarding.onboardingprofile')),
            ],
            options={
                'db_table': 'logs_medication',
                'ordering': ['time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flow', models.CharField(blank=True, max_length=12, null=True)),
                ('blood_color', models.CharField(blank=True, max_length=12, null=True)),
                ('clots_present', models.BooleanField(blank=True, null=True)),
                ('clot_size', models.CharField(blank=True, max_length=10, null=True)),
                ('cramps', models.CharField(blank=True, max_length=10, null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('products', models.JSONField(blank=True, default=list)),
                ('mood', models.CharField(blank=True, max_length=12, null=True)),
                ('energy', models.CharField(blank=True, max_length=10, null=True)),
                ('libido', models.CharField(blank=True, max_length=10, null=True)),
                ('cervical_mucus', models.CharField(blank=True, max_length=12, null=True)),
                ('bbt_celsius', models.FloatField(blank=True, null=True)),
                ('bbt_time', models.CharField(blank=True, max_length=5, null=True)),
                ('lh_test', models.CharField(blank=True, max_length=10, null=True)),
                ('intercourse', models.BooleanField(blank=True, null=True)),
                ('sleep', models.CharField(blank=True, max_length=10, null=True)),
                ('fatigue', models.CharField(blank=True, max_length=10, null=True)),
                ('cravings', models.CharField(blank=True, max_length=10, null=True)),
                ('water_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='onboarding.onboardingprofile')),
            ],
            options={
                'db_table': 'logs_daily_log',
                'constraints': [models.UniqueConstraint(fields=('profile', 'date'), name='uniq_log_per_day')],
            },
        ),
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('skipped', 'Skipped')], max_length=8)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='logs.medication')),
            ],
            options={
                'db_table': 'logs_medication_intake',
                'constraints': [models.UniqueConstraint(fields=('medication', 'date'), name='uniq_intake_per_day')],
            },
        ),
    ]
