import { apiRequest } from "../api/client";
import { localISODate } from "../cycle";

export interface PhaseInsight {
  phase: string;
  summary: string;
  tips: string[];
  generatedAt: string;
}

export interface PhaseInsightResponse {
  status: "ready" | "unavailable" | "no_phase";
  insight: PhaseInsight | null;
}

export const getPhaseInsight = (
  dateOrSignal?: string | AbortSignal,
  signal?: AbortSignal,
) => {
  const date =
    typeof dateOrSignal === "string"
      ? dateOrSignal
      : localISODate();

  const requestSignal =
    typeof dateOrSignal === "string"
      ? signal
      : dateOrSignal;

  return apiRequest<PhaseInsightResponse>("/api/v1/insights/phase", {
    query: { date },
    signal: requestSignal,
  });
};
export const askAva = (question: string) =>
  apiRequest<{ answer: string }>("/api/v1/insights/ask", {
    method: "POST",
    query: { date: localISODate() },
    body: { question },
  });

  export type TipCategory = "hydration" | "nutrition" | "movement" | "sleep" | "rest" | "pain_relief" | "mood" | "care";

export interface PhaseTip {
  title: string;
  text: string;
  category: TipCategory;
}

export interface PhaseTipsResponse {
  status: "ready" | "unavailable" | "no_phase";
  phase: string | null;
  tips: PhaseTip[];
  basedOn: { logDays: number; healthProfile: boolean } | null;
}

/** Tips written from the user's health profile and recent logs (generated by the backend, cached per day). */
export const getPhaseTips = (date: string, signal?: AbortSignal) =>
  apiRequest<PhaseTipsResponse>("/api/v1/insights/tips", { query: { date }, signal });
