import { Apple, Droplets, Heart, HeartPulse, Flame, Moon, Smile, Sparkles, X, type LucideIcon } from "lucide-react";
import { useCallback, useId, useRef } from "react";
import { useAsync } from "../../../../hooks/useAsync";
import { getPhaseTips, type TipCategory } from "../../../../services/insights";
import { LuModal } from "./LuModal";

const ICONS: Record<TipCategory, { icon: LucideIcon; className: string }> = {
  hydration: { icon: Droplets, className: "text-[#3B82F6]" },
  nutrition: { icon: Apple, className: "text-[#16A34A]" },
  movement: { icon: Heart, className: "text-[#E11D48]" },
  sleep: { icon: Moon, className: "text-[#6366F1]" },
  rest: { icon: Moon, className: "text-[#8B5CF6]" },
  pain_relief: { icon: Flame, className: "text-[#EA580C]" },
  mood: { icon: Smile, className: "text-[#D97706]" },
  care: { icon: HeartPulse, className: "text-[#DB2777]" },
};

interface PhaseTipsModalProps {
  /** "Menstrual", "Ovulation", ... shown as "<Phase> Phase Wellness Tips". */
  phaseLabel: string;
  /** The day the dashboard is showing (YYYY-MM-DD). */
  day: string;
  onClose: () => void;
}

/** Wellness tips dialog. The tips are generated by the backend from the user's health profile and recent logs. */
export function PhaseTipsModal({ phaseLabel, day, onClose }: PhaseTipsModalProps) {
  const titleId = useId();
  const descId = useId();
  const closeBtn = useRef<HTMLButtonElement>(null);
  const load = useCallback((signal: AbortSignal) => getPhaseTips(day, signal), [day]);
  const tips = useAsync(load);

  const ready = tips.status === "ready" && tips.data?.status === "ready" && tips.data.tips.length > 0;
  const loading = tips.status === "loading";
  const basedOn = tips.data?.basedOn;

  return (
    <LuModal labelledBy={titleId} describedBy={descId} onClose={onClose} initialFocus={closeBtn} className="flex max-h-[92dvh] flex-col overflow-hidden sm:max-w-[520px]">
      <header className="flex items-start justify-between gap-4 bg-gradient-to-r from-[#FDF2F8] to-[#F5F0FF] px-[clamp(18px,2vw,26px)] py-[clamp(16px,1.6vw,22px)]">
        <div className="flex min-w-0 items-start gap-3">
          <span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-lu-brand text-white">
            <Sparkles className="size-[18px]" aria-hidden="true" />
          </span>
          <div className="min-w-0">
            <h2 id={titleId} className="text-lu-body font-semibold text-lu-ink">{phaseLabel} Phase Wellness Tips</h2>
            <p id={descId} className="mt-0.5 text-lu-label text-lu-ink-muted">Expert recommendations for your cycle</p>
          </div>
        </div>
        <button ref={closeBtn} type="button" onClick={onClose} aria-label="Close" className="flex size-9 shrink-0 items-center justify-center rounded-full text-lu-ink-muted transition-colors hover:bg-white/70 hover:text-lu-brand-strong">
          <X className="size-[18px]" strokeWidth={2.2} />
        </button>
      </header>

      <div className="min-h-0 flex-1 overflow-y-auto px-[clamp(18px,2vw,26px)] py-4" aria-live="polite" aria-busy={loading}>
        {loading && (
          <ul className="grid gap-3" aria-label="Preparing your tips">
            {[0, 1, 2, 3].map((i) => (
              <li key={i} className="h-[92px] animate-pulse rounded-[16px] bg-[#FFF7FA]" />
            ))}
          </ul>
        )}

        {ready && (
          <>
            <ul className="grid gap-3">
              {tips.data!.tips.map(({ title, text, category }) => {
                const { icon: Icon, className } = ICONS[category] ?? ICONS.care;
                return (
                  <li key={title} className="flex items-start gap-3 rounded-[16px] border border-lu-brand-line bg-[#FFF9FB] p-4">
                    <span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-white shadow-lu-pill">
                      <Icon className={`size-[16px] ${className}`} aria-hidden="true" />
                    </span>
                    <div className="min-w-0">
                      <h3 className="text-lu-label font-semibold text-lu-ink">{title}</h3>
                      <p className="mt-1 text-lu-caption leading-relaxed text-lu-ink-muted">{text}</p>
                    </div>
                  </li>
                );
              })}
            </ul>
            {basedOn && (
              <p className="mt-3 text-lu-caption text-lu-ink-muted">
                {basedOn.logDays > 0
                  ? `Written from your health details and ${basedOn.logDays} ${basedOn.logDays === 1 ? "day" : "days"} of logs. Log more to make it more personal.`
                  : "Written from your health details. Log your days to make it more personal."}
              </p>
            )}
          </>
        )}

        {!loading && !ready && (
          <p role="alert" className="rounded-[16px] bg-[#FFF7FA] p-4 text-lu-label text-lu-ink-muted">
            {tips.status === "ready" && tips.data?.status === "no_phase"
              ? "Log a period to get tips for your current phase."
              : "Your tips aren't available right now."}{" "}
            {tips.data?.status !== "no_phase" && (
              <button type="button" onClick={tips.refetch} className="font-semibold text-lu-brand-strong underline">
                Try again
              </button>
            )}
          </p>
        )}

        <p className="mt-3 text-lu-caption text-lu-ink-muted">General wellness information, not medical advice.</p>
      </div>

      <footer className="flex justify-end border-t border-lu-line px-[clamp(18px,2vw,26px)] py-4">
        <button type="button" onClick={onClose} className="rounded-full bg-lu-brand px-7 py-2.5 text-lu-label font-semibold text-white shadow-lu-glow transition-colors hover:bg-lu-brand-strong">
          Got it
        </button>
      </footer>
    </LuModal>
  );
}