# Generated by Django 6.1.1 on 2026-10-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start', models.DateField()),
                ('phase', models.CharField(max_length=12)),
                ('summary', models.TextField()),
                ('tips', models.JSONField(default=list)),
                ('facts', models.JSONField(default=dict)),
                ('facts_hash', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=80)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_insights', to='onboarding.onboardingprofile')),
            ],
            options={
                'db_table': 'insights_phase_insight',
                'constraints': [models.UniqueConstraint(fields=('profile', 'cycle_start', 'phase'), name='uniq_insight_per_phase')],
            },
        ),
    ]
