# Generated by Django 6.1.1 on 2026-10-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('user', 'User')], default='user', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='onboarding.onboardingprofile')),
            ],
            options={
                'db_table': 'cycles_period',
                'ordering': ['start_date'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'start_date'), name='uniq_period_start_per_profile'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='period_end_not_before_start')],
            },
        ),
    ]
