# Generated by Django 6.1.1 on 2026-10-01 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period_onboarding_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_draft',
            },
        ),
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_period', models.DateField()),
                ('cycle_length_option', models.CharField(choices=[('known', 'Known'), ('unsure', 'Unsure'), ('varies', 'Varies')], max_length=10)),
                ('cycle_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('period_regularity', models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular'), ('unknown', 'Unknown')], max_length=10)),
                ('period_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('use_manual_duration', models.BooleanField(default=False)),
                ('manual_period_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('medical_conditions', models.JSONField(blank=True, default=list)),
                ('other_medical_condition', models.CharField(blank=True, default='', max_length=255)),
                ('taking_medication', models.BooleanField(blank=True, null=True)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('custom_symptom', models.CharField(blank=True, default='', max_length=255)),
                ('moods', models.JSONField(blank=True, default=list)),
                ('custom_mood', models.CharField(blank=True, default='', max_length=255)),
                ('period_reminder', models.BooleanField(default=False)),
                ('period_reminder_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ovulation_reminder', models.BooleanField(default=False)),
                ('ovulation_reminder_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_control', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('prefer-not-to-say', 'Prefer not to say')], default='', max_length=20)),
                ('birth_control_category', models.CharField(blank=True, choices=[('natural', 'Natural'), ('hormonal', 'Hormonal'), ('other', 'Other')], default='', max_length=10)),
                ('birth_control_method', models.CharField(blank=True, default='', max_length=100)),
                ('birth_control_custom_method', models.CharField(blank=True, default='', max_length=100)),
                ('fertility_goal', models.CharField(blank=True, choices=[('trying-to-conceive', 'Trying to conceive'), ('pregnancy-prevention', 'Pregnancy prevention'), ('understand-cycle', 'Understand cycle')], default='', max_length=25)),
                ('fertility_tracking', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField()),
                ('payload_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_profile',
            },
        ),
    ]
